### ISSUE TITLE
In rush current on GPS and Si5351 trips CPU under voltage

### ISSUE THREAD

**Issue by TimMW1** [adecarolis/K1FM-Pico-Balloon#1] opened 2020-02-15 00:54 UTC
While using the latest version of Orion with the turn on FETs enabled, the CPU gets into a reset loop due to a drop on the 3v rail when the GPS and Si PLL get enabled.  A soft start cap on the FET gate an/or more Bulk would fix this issue.

**Comment by mrpatrick1991** [comment] 2020-10-03 06:13
Can confirm a reboot loop on start with V1.3 of the board running either the GeminiWSPR or OrionWSPR software. 

Attempted to correct this by adding 300uF capacitors on the 3v rail as well as soft-start on the mosfet gates. The behavior was not changed.

Running simple test programs on the si5351 and gps allow me to turn on and use both simultaneously without issue, so I suspect it is a software problem (?)

Any insight would be appreciated.

**Comment by adecarolis** [comment] 2020-10-03 11:49
Hello Tim and Patrick. Sorry for the inconvenience.
I apologize for replying so late but I never noticed this issue until Patrick sent me a direct email (thanks for that).

I am not familiar with any reboots but I will try to assemble another board ASAP and try to reproduce the issue.
Meanwhile, since you clearly have a problem, please just bypass those FETs, like so: https://imgur.com/a/XCQ49I2
In this configuration, the board must work as it flew successfully at least 3 times. 

The only issue I had related to those FETs was software related. I remember that during flight, if I unpowered the si5351 and/or the GPS I would not always be able to restart them in a functional state unless I rebooted the micro, which was unfortunate and inconvenient. I attributed the issue to I2C (apparently you can't simply power off a connected I2C device and then simply power it back on). For this reason, in GeminWspr I immediately power on both devices and leave them powered all along. The good news is that in the current configuration there is more than enough current to have all the components powered at all times, so bypassing the FETs isn't a problem. I normally don't even install them anymore.

The reason why I introduced them was because they were requested by other users of the board. I also was planning to leverage them in a subsequent release that uses a step-up regulator capable of powering the whole thing on a single panel. For now, you don't need them, so feel free to bypass them altogether. In any case, I will assemble a new board ASAP and try to reproduce the issue you describe. I will post updates here.

Thanks again!

**Comment by mrpatrick1991** [comment] 2020-10-05 23:18
Hey - thanks for the reply! I'll report back after trying to bypass the MOSFET's.

**Comment by mrpatrick1991** [comment] 2020-10-09 01:29
Bypassing the MOSFET's does not appear to change the reset behavior. This is with a bench 3.3v supply connected to the 3.3v rail, and the OrionWSPR V1.0 software with the K1FM board definition. 

Does anyone have any other ideas?

**Comment by adecarolis** [comment] 2020-10-18 23:11
Hello,

I was 100% sure in the first place that there isn't an overcurrent issue but in order to triple check I just finished assembling another board. **No issues were found: TX is OK, GPS is OK, drawn current never exceeds 50mA at 3.3V**.

Your issues might or might not be related. When there is a short or any other soldering defect more often than not you end up with issues similar to the one you describe. This is precisely why I recommend an incremental assembly procedure: you might want to catch an eventual issue early on rather than at the end of the build.
To troubleshoot, I suggest removing components applying the procedure in reverse order until you reach a point where the overcurrent doesn't happen anymore. At that point you will know where the problem is.

I'm closing the issue. Good luck!

**Closed as completed by adecarolis** 2020-10-18 23:11 UTC
